listen: 0.0.0.0:10443

tls:
  cert: /home/zhihao/hy2.crt
  key: /home/zhihao/hy2.key

auth:
  type: password
  password: test

masquerade:
  type: proxy
  proxy:
    url: https://bing.com/
    rewriteHost: true
